In [152]:
import numpy as np
import pandas as pd
from datetime import datetime

In [153]:
f = open("IPO_Data.csv",encoding="utf-8", errors='replace')
data = pd.read_csv(f)
data.head

c:\users\matt huo\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1342,1425,1432,1543,1546,1549,1551,1552,1553,1562,1587,1588,1605,1608,1615,1619,1620,1621,1622,1629,1630,1632,1633,1640,1641,1642,1643,1644,1646) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

<bound method NDFrame.head of      Symbol  DaysBetterThanSP  daysProfit daysProfitGrouped  exactDiffernce  \
0         A               122         249              200+             NaN
1       AAC               131         262              200+           232.0
2      AAOI               125         262              200+          6054.0
3       AAP               128         261              200+             NaN
4       AAT               123         127         100 - 149           181.0
...     ...               ...         ...               ...             ...
3757   ZUMZ               139         261              200+             NaN
3758    ZUO                 5           7            0 - 49             NaN
3759     ZX               102          25            0 - 49          1035.0
3760   ZYME               115          19            0 - 49             NaN
3761   ZYNE               104          42            0 - 49          3108.0

      Year  Month  Day  dayOfWeek  closeDay0  ...  usableCEOAge  \
0     1999     11   18          3    28.6358  ...         Blank
1     2014     10    2          3    18.5000  ...       40 - 49
2     2013      9   26          3     9.9600  ...         Blank
3     2001     11   29          3    13.9000  ...         Blank
4     2011      1   13          3    21.2500  ...         Blank
...    ...    ...  ...        ...        ...  ...           ...
3757  2005      5    6          4    12.4350  ...         Blank
3758  2018      4   12          3    20.0000  ...           NaN
3759  2011      5   12          3     5.8500  ...       Unknown
3760  2017      4   28          4    13.0000  ...       Unknown
3761  2015      8    5          2    16.2500  ...       50 - 59

      usableCEOGender  usablePresidentAge  usablePresidentGender  \
0               Blank               Blank                  Blank
1                male               Blank                  Blank
2               Blank               Blank                  Blank
3               Blank               Blank                  Blank
4               Blank               Blank                  Blank
...               ...                 ...                    ...
3757            Blank               Blank                  Blank
3758      mostly_male             Unknown                Unknown
3759          Unknown             Unknown                Unknown
3760          Unknown             Unknown                Unknown
3761             male             50 - 59                 female

      FoundingDateGrouped  yearDifferenceGrouped  Profitable  Safe  \
0             1951 - 2000                Unknown           1     0
1          2011 - present                Unknown           1     1
2             1951 - 2000                Unknown           1     0
3             1901 - 1950                Unknown           1     0
4             2001 - 2010                Unknown           0     0
...                   ...                    ...         ...   ...
3757          1951 - 2000                Unknown           1     1
3758          2001 - 2010                Unknown           0     0
3759          2001 - 2010                Unknown           0     0
3760          2001 - 2010                Unknown           0     0
3761          2001 - 2010                Unknown           0     0

      HomeRunDay  HomeRun
0           77.0        1
1            NaN        0
2            NaN        0
3            NaN        0
4            NaN        0
...          ...      ...
3757       234.0        1
3758         NaN        0
3759         NaN        0
3760         NaN        0
3761         NaN        0

[3762 rows x 1664 columns]>

In [154]:
data.shape

(3762, 1664)

In [155]:
d = data
index_names = d[(d['Year'] < 2012)].index
d.drop(index_names, inplace = True)

In [156]:
d

,Symbol,DaysBetterThanSP,daysProfit,daysProfitGrouped,exactDiffernce,Year,Month,Day,dayOfWeek,closeDay0,...,usableCEOAge,usableCEOGender,usablePresidentAge,usablePresidentGender,FoundingDateGrouped,yearDifferenceGrouped,Profitable,Safe,HomeRunDay,HomeRun
1,AAC,131,262,200+,232.0,2014,10,2,3,18.50,...,40 - 49,male,Blank,Blank,2011 - present,Unknown,1,1,NaN,0
2,AAOI,125,262,200+,6054.0,2013,9,26,3,9.96,...,Blank,Blank,Blank,Blank,1951 - 2000,Unknown,1,0,NaN,0
10,ABBV,138,242,200+,-22.0,2012,12,10,0,35.00,...,Blank,Blank,Blank,Blank,2011 - present,Unknown,1,1,NaN,0
12,ABDC,112,24,0 - 49,NaN,2014,5,9,4,15.05,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,0,0,NaN,0
17,ABLX,70,128,100 - 149,5952.0,2017,10,20,4,19.50,...,60 - 69,male,Unknown,Unknown,2001 - 2010,Unknown,0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3755,ZTO,135,3,0 - 49,NaN,2016,10,27,3,16.57,...,40 - 49,unknown,40 - 49,unknown,2011 - present,Unknown,0,1,NaN,0
3756,ZTS,115,226,200+,NaN,2013,2,1,4,31.01,...,60 - 69,male,Blank,Blank,2011 - present,Unknown,1,0,NaN,0
3758,ZUO,5,7,0 - 49,NaN,2018,4,12,3,20.00,...,NaN,mostly_male,Unknown,Unknown,2001 - 2010,Unknown,0,0,NaN,0
3760,ZYME,115,19,0 - 49,NaN,2017,4,28,4,13.00,...,Unknown,Unknown,Unknown,Unknown,2001 - 2010,Unknown,0,0,NaN,0
3761,ZYNE,104,42,0 - 49,3108.0,2015,8,5,2,16.25,...,50 - 59,male,50 - 59,female,2001 - 2010,Unknown,0,0,NaN,0

In [157]:
list(data.columns)

['Symbol',
 'DaysBetterThanSP',
 'daysProfit',
 'daysProfitGrouped',
 'exactDiffernce',
 'Year',
 'Month',
 'Day',
 'dayOfWeek',
 'closeDay0',
 'highDay0',
 'openDay0',
 'lowDay0',
 'volumeDay0',
 'closeDay1',
 'highDay1',
 'openDay1',
 'lowDay1',
 'volumeDay1',
 'closeDay2',
 'highDay2',
 'openDay2',
 'lowDay2',
 'volumeDay2',
 'closeDay3',
 'highDay3',
 'openDay3',
 'lowDay3',
 'volumeDay3',
 'closeDay4',
 'highDay4',
 'openDay4',
 'lowDay4',
 'volumeDay4',
 'closeDay5',
 'highDay5',
 'openDay5',
 'lowDay5',
 'volumeDay5',
 'closeDay6',
 'highDay6',
 'openDay6',
 'lowDay6',
 'volumeDay6',
 'closeDay7',
 'highDay7',
 'openDay7',
 'lowDay7',
 'volumeDay7',
 'closeDay8',
 'highDay8',
 'openDay8',
 'lowDay8',
 'volumeDay8',
 'closeDay9',
 'highDay9',
 'openDay9',
 'lowDay9',
 'volumeDay9',
 'closeDay10',
 'highDay10',
 'openDay10',
 'lowDay10',
 'volumeDay10',
 'closeDay11',
 'highDay11',
 'openDay11',
 'lowDay11',
 'volumeDay11',
 'closeDay12',
 'highDay12',
 'openDay12',
 'lowDay12',
 'volumeDay12',
 'closeDay13',
 'highDay13',
 'openDay13',
 'lowDay13',
 'volumeDay13',
 'closeDay14',
 'highDay14',
 'openDay14',
 'lowDay14',
 'volumeDay14',
 'closeDay15',
 'highDay15',
 'openDay15',
 'lowDay15',
 'volumeDay15',
 'closeDay16',
 'highDay16',
 'openDay16',
 'lowDay16',
 'volumeDay16',
 'closeDay17',
 'highDay17',
 'openDay17',
 'lowDay17',
 'volumeDay17',
 'closeDay18',
 'highDay18',
 'openDay18',
 'lowDay18',
 'volumeDay18',
 'closeDay19',
 'highDay19',
 'openDay19',
 'lowDay19',
 'volumeDay19',
 'closeDay20',
 'highDay20',
 'openDay20',
 'lowDay20',
 'volumeDay20',
 'closeDay21',
 'highDay21',
 'openDay21',
 'lowDay21',
 'volumeDay21',
 'closeDay22',
 'highDay22',
 'openDay22',
 'lowDay22',
 'volumeDay22',
 'closeDay23',
 'highDay23',
 'openDay23',
 'lowDay23',
 'volumeDay23',
 'closeDay24',
 'highDay24',
 'openDay24',
 'lowDay24',
 'volumeDay24',
 'closeDay25',
 'highDay25',
 'openDay25',
 'lowDay25',
 'volumeDay25',
 'closeDay26',
 'highDay26',
 'openDay26',
 'lowDay26',
 'volumeDay26',
 'closeDay27',
 'highDay27',
 'openDay27',
 'lowDay27',
 'volumeDay27',
 'closeDay28',
 'highDay28',
 'openDay28',
 'lowDay28',
 'volumeDay28',
 'closeDay29',
 'highDay29',
 'openDay29',
 'lowDay29',
 'volumeDay29',
 'closeDay30',
 'highDay30',
 'openDay30',
 'lowDay30',
 'volumeDay30',
 'closeDay31',
 'highDay31',
 'openDay31',
 'lowDay31',
 'volumeDay31',
 'closeDay32',
 'highDay32',
 'openDay32',
 'lowDay32',
 'volumeDay32',
 'closeDay33',
 'highDay33',
 'openDay33',
 'lowDay33',
 'volumeDay33',
 'closeDay34',
 'highDay34',
 'openDay34',
 'lowDay34',
 'volumeDay34',
 'closeDay35',
 'highDay35',
 'openDay35',
 'lowDay35',
 'volumeDay35',
 'closeDay36',
 'highDay36',
 'openDay36',
 'lowDay36',
 'volumeDay36',
 'closeDay37',
 'highDay37',
 'openDay37',
 'lowDay37',
 'volumeDay37',
 'closeDay38',
 'highDay38',
 'openDay38',
 'lowDay38',
 'volumeDay38',
 'closeDay39',
 'highDay39',
 'openDay39',
 'lowDay39',
 'volumeDay39',
 'closeDay40',
 'highDay40',
 'openDay40',
 'lowDay40',
 'volumeDay40',
 'closeDay41',
 'highDay41',
 'openDay41',
 'lowDay41',
 'volumeDay41',
 'closeDay42',
 'highDay42',
 'openDay42',
 'lowDay42',
 'volumeDay42',
 'closeDay43',
 'highDay43',
 'openDay43',
 'lowDay43',
 'volumeDay43',
 'closeDay44',
 'highDay44',
 'openDay44',
 'lowDay44',
 'volumeDay44',
 'closeDay45',
 'highDay45',
 'openDay45',
 'lowDay45',
 'volumeDay45',
 'closeDay46',
 'highDay46',
 'openDay46',
 'lowDay46',
 'volumeDay46',
 'closeDay47',
 'highDay47',
 'openDay47',
 'lowDay47',
 'volumeDay47',
 'closeDay48',
 'highDay48',
 'openDay48',
 'lowDay48',
 'volumeDay48',
 'closeDay49',
 'highDay49',
 'openDay49',
 'lowDay49',
 'volumeDay49',
 'closeDay50',
 'highDay50',
 'openDay50',
 'lowDay50',
 'volumeDay50',
 'closeDay51',
 'highDay51',
 'openDay51',
 'lowDay51',
 'volumeDay51',
 'closeDay52',
 'highDay52',
 'openDay52',
 'lowDay52',
 'volumeDay52',
 'closeDay53',
 'highDay53',
 'openDay53',
 'lowDay53',
 'volumeDay53',
 'closeDay54',
 'highDay54',
 'openDay54',
 'lowDay54',
 'volumeDay54',
 'closeDay55',
 'highDay55',
 'openDay55',
 'lowDay55',
 'volumeDay55',
 'closeDay56',
 'highDay56',
 'openDay56',
 'lowDay56',
 'volumeDay56',
 'closeDay57',
 'highDay57',
 'openDay57',
 'lowDay57',
 'volumeDay57',
 'closeDay58',
 'highDay58',
 'openDay58',
 'lowDay58',
 'volumeDay58',
 'closeDay59',
 'highDay59',
 'openDay59',
 'lowDay59',
 'volumeDay59',
 'closeDay60',
 'highDay60',
 'openDay60',
 'lowDay60',
 'volumeDay60',
 'closeDay61',
 'highDay61',
 'openDay61',
 'lowDay61',
 'volumeDay61',
 'closeDay62',
 'highDay62',
 'openDay62',
 'lowDay62',
 'volumeDay62',
 'closeDay63',
 'highDay63',
 'openDay63',
 'lowDay63',
 'volumeDay63',
 'closeDay64',
 'highDay64',
 'openDay64',
 'lowDay64',
 'volumeDay64',
 'closeDay65',
 'highDay65',
 'openDay65',
 'lowDay65',
 'volumeDay65',
 'closeDay66',
 'highDay66',
 'openDay66',
 'lowDay66',
 'volumeDay66',
 'closeDay67',
 'highDay67',
 'openDay67',
 'lowDay67',
 'volumeDay67',
 'closeDay68',
 'highDay68',
 'openDay68',
 'lowDay68',
 'volumeDay68',
 'closeDay69',
 'highDay69',
 'openDay69',
 'lowDay69',
 'volumeDay69',
 'closeDay70',
 'highDay70',
 'openDay70',
 'lowDay70',
 'volumeDay70',
 'closeDay71',
 'highDay71',
 'openDay71',
 'lowDay71',
 'volumeDay71',
 'closeDay72',
 'highDay72',
 'openDay72',
 'lowDay72',
 'volumeDay72',
 'closeDay73',
 'highDay73',
 'openDay73',
 'lowDay73',
 'volumeDay73',
 'closeDay74',
 'highDay74',
 'openDay74',
 'lowDay74',
 'volumeDay74',
 'closeDay75',
 'highDay75',
 'openDay75',
 'lowDay75',
 'volumeDay75',
 'closeDay76',
 'highDay76',
 'openDay76',
 'lowDay76',
 'volumeDay76',
 'closeDay77',
 'highDay77',
 'openDay77',
 'lowDay77',
 'volumeDay77',
 'closeDay78',
 'highDay78',
 'openDay78',
 'lowDay78',
 'volumeDay78',
 'closeDay79',
 'highDay79',
 'openDay79',
 'lowDay79',
 'volumeDay79',
 'closeDay80',
 'highDay80',
 'openDay80',
 'lowDay80',
 'volumeDay80',
 'closeDay81',
 'highDay81',
 'openDay81',
 'lowDay81',
 'volumeDay81',
 'closeDay82',
 'highDay82',
 'openDay82',
 'lowDay82',
 'volumeDay82',
 'closeDay83',
 'highDay83',
 'openDay83',
 'lowDay83',
 'volumeDay83',
 'closeDay84',
 'highDay84',
 'openDay84',
 'lowDay84',
 'volumeDay84',
 'closeDay85',
 'highDay85',
 'openDay85',
 'lowDay85',
 'volumeDay85',
 'closeDay86',
 'highDay86',
 'openDay86',
 'lowDay86',
 'volumeDay86',
 'closeDay87',
 'highDay87',
 'openDay87',
 'lowDay87',
 'volumeDay87',
 'closeDay88',
 'highDay88',
 'openDay88',
 'lowDay88',
 'volumeDay88',
 'closeDay89',
 'highDay89',
 'openDay89',
 'lowDay89',
 'volumeDay89',
 'closeDay90',
 'highDay90',
 'openDay90',
 'lowDay90',
 'volumeDay90',
 'closeDay91',
 'highDay91',
 'openDay91',
 'lowDay91',
 'volumeDay91',
 'closeDay92',
 'highDay92',
 'openDay92',
 'lowDay92',
 'volumeDay92',
 'closeDay93',
 'highDay93',
 'openDay93',
 'lowDay93',
 'volumeDay93',
 'closeDay94',
 'highDay94',
 'openDay94',
 'lowDay94',
 'volumeDay94',
 'closeDay95',
 'highDay95',
 'openDay95',
 'lowDay95',
 'volumeDay95',
 'closeDay96',
 'highDay96',
 'openDay96',
 'lowDay96',
 'volumeDay96',
 'closeDay97',
 'highDay97',
 'openDay97',
 'lowDay97',
 'volumeDay97',
 'closeDay98',
 'highDay98',
 'openDay98',
 'lowDay98',
 'volumeDay98',
 'closeDay99',
 'highDay99',
 'openDay99',
 'lowDay99',
 'volumeDay99',
 'closeDay100',
 'highDay100',
 'openDay100',
 'lowDay100',
 'volumeDay100',
 'closeDay101',
 'highDay101',
 'openDay101',
 'lowDay101',
 'volumeDay101',
 'closeDay102',
 'highDay102',
 'openDay102',
 'lowDay102',
 'volumeDay102',
 'closeDay103',
 'highDay103',
 'openDay103',
 'lowDay103',
 'volumeDay103',
 'closeDay104',
 'highDay104',
 'openDay104',
 'lowDay104',
 'volumeDay104',
 'closeDay105',
 'highDay105',
 'openDay105',
 'lowDay105',
 'volumeDay105',
 'closeDay106',
 'highDay106',
 'openDay106',
 'lowDay106',
 'volumeDay106',
 'closeDay107',
 'highDay107',
 'openDay107',
 'lowDay107',
 'volumeDay107',
 'closeDay108',
 'highDay108',
 'openDay108',
 'lowDay108',
 'volumeDay108',
 'closeDay109',
 'highDay109',
 'openDay109',
 'lowDay109',
 'volumeDay109',
 'closeDay110',
 'highDay110',
 'openDay110',
 'lowDay110',
 'volumeDay110',
 'closeDay111',
 'highDay111',
 'openDay111',
 'lowDay111',
 'volumeDay111',
 'closeDay112',
 'highDay112',
 'openDay112',
 'lowDay112',
 'volumeDay112',
 'closeDay113',
 'highDay113',
 'openDay113',
 'lowDay113',
 'volumeDay113',
 'closeDay114',
 'highDay114',
 'openDay114',
 'lowDay114',
 'volumeDay114',
 'closeDay115',
 'highDay115',
 'openDay115',
 'lowDay115',
 'volumeDay115',
 'closeDay116',
 'highDay116',
 'openDay116',
 'lowDay116',
 'volumeDay116',
 'closeDay117',
 'highDay117',
 'openDay117',
 'lowDay117',
 'volumeDay117',
 'closeDay118',
 'highDay118',
 'openDay118',
 'lowDay118',
 'volumeDay118',
 'closeDay119',
 'highDay119',
 'openDay119',
 'lowDay119',
 'volumeDay119',
 'closeDay120',
 'highDay120',
 'openDay120',
 'lowDay120',
 'volumeDay120',
 'closeDay121',
 'highDay121',
 'openDay121',
 'lowDay121',
 'volumeDay121',
 'closeDay122',
 'highDay122',
 'openDay122',
 'lowDay122',
 'volumeDay122',
 'closeDay123',
 'highDay123',
 'openDay123',
 'lowDay123',
 'volumeDay123',
 'closeDay124',
 'highDay124',
 'openDay124',
 'lowDay124',
 'volumeDay124',
 'closeDay125',
 'highDay125',
 'openDay125',
 'lowDay125',
 'volumeDay125',
 'closeDay126',
 'highDay126',
 'openDay126',
 'lowDay126',
 'volumeDay126',
 'closeDay127',
 'highDay127',
 'openDay127',
 'lowDay127',
 'volumeDay127',
 'closeDay128',
 'highDay128',
 'openDay128',
 'lowDay128',
 'volumeDay128',
 'closeDay129',
 'highDay129',
 'openDay129',
 'lowDay129',
 'volumeDay129',
 'closeDay130',
 'highDay130',
 'openDay130',
 'lowDay130',
 'volumeDay130',
 'closeDay131',
 'highDay131',
 'openDay131',
 'lowDay131',
 'volumeDay131',
 'closeDay132',
 'highDay132',
 'openDay132',
 'lowDay132',
 'volumeDay132',
 'closeDay133',
 'highDay133',
 'openDay133',
 'lowDay133',
 'volumeDay133',
 'closeDay134',
 'highDay134',
 'openDay134',
 'lowDay134',
 'volumeDay134',
 'closeDay135',
 'highDay135',
 'openDay135',
 'lowDay135',
 'volumeDay135',
 'closeDay136',
 'highDay136',
 'openDay136',
 'lowDay136',
 'volumeDay136',
 'closeDay137',
 'highDay137',
 'openDay137',
 'lowDay137',
 'volumeDay137',
 'closeDay138',
 'highDay138',
 'openDay138',
 'lowDay138',
 'volumeDay138',
 'closeDay139',
 'highDay139',
 'openDay139',
 'lowDay139',
 'volumeDay139',
 'closeDay140',
 'highDay140',
 'openDay140',
 'lowDay140',
 'volumeDay140',
 'closeDay141',
 'highDay141',
 'openDay141',
 'lowDay141',
 'volumeDay141',
 'closeDay142',
 'highDay142',
 'openDay142',
 'lowDay142',
 'volumeDay142',
 'closeDay143',
 'highDay143',
 'openDay143',
 'lowDay143',
 'volumeDay143',
 'closeDay144',
 'highDay144',
 'openDay144',
 'lowDay144',
 'volumeDay144',
 'closeDay145',
 'highDay145',
 'openDay145',
 'lowDay145',
 'volumeDay145',
 'closeDay146',
 'highDay146',
 'openDay146',
 'lowDay146',
 'volumeDay146',
 'closeDay147',
 'highDay147',
 'openDay147',
 'lowDay147',
 'volumeDay147',
 'closeDay148',
 'highDay148',
 'openDay148',
 'lowDay148',
 'volumeDay148',
 'closeDay149',
 'highDay149',
 'openDay149',
 'lowDay149',
 'volumeDay149',
 'closeDay150',
 'highDay150',
 'openDay150',
 'lowDay150',
 'volumeDay150',
 'closeDay151',
 'highDay151',
 'openDay151',
 'lowDay151',
 'volumeDay151',
 'closeDay152',
 'highDay152',
 'openDay152',
 'lowDay152',
 'volumeDay152',
 'closeDay153',
 'highDay153',
 'openDay153',
 'lowDay153',
 'volumeDay153',
 'closeDay154',
 'highDay154',
 'openDay154',
 'lowDay154',
 'volumeDay154',
 'closeDay155',
 'highDay155',
 'openDay155',
 'lowDay155',
 'volumeDay155',
 'closeDay156',
 'highDay156',
 'openDay156',
 'lowDay156',
 'volumeDay156',
 'closeDay157',
 'highDay157',
 'openDay157',
 'lowDay157',
 'volumeDay157',
 'closeDay158',
 'highDay158',
 'openDay158',
 'lowDay158',
 'volumeDay158',
 'closeDay159',
 'highDay159',
 'openDay159',
 'lowDay159',
 'volumeDay159',
 'closeDay160',
 'highDay160',
 'openDay160',
 'lowDay160',
 'volumeDay160',
 'closeDay161',
 'highDay161',
 'openDay161',
 'lowDay161',
 'volumeDay161',
 'closeDay162',
 'highDay162',
 'openDay162',
 'lowDay162',
 'volumeDay162',
 'closeDay163',
 'highDay163',
 'openDay163',
 'lowDay163',
 'volumeDay163',
 'closeDay164',
 'highDay164',
 'openDay164',
 'lowDay164',
 'volumeDay164',
 'closeDay165',
 'highDay165',
 'openDay165',
 'lowDay165',
 'volumeDay165',
 'closeDay166',
 'highDay166',
 'openDay166',
 'lowDay166',
 'volumeDay166',
 'closeDay167',
 'highDay167',
 'openDay167',
 'lowDay167',
 'volumeDay167',
 'closeDay168',
 'highDay168',
 'openDay168',
 'lowDay168',
 'volumeDay168',
 'closeDay169',
 'highDay169',
 'openDay169',
 'lowDay169',
 'volumeDay169',
 'closeDay170',
 'highDay170',
 'openDay170',
 'lowDay170',
 'volumeDay170',
 'closeDay171',
 'highDay171',
 'openDay171',
 'lowDay171',
 'volumeDay171',
 'closeDay172',
 'highDay172',
 'openDay172',
 'lowDay172',
 'volumeDay172',
 'closeDay173',
 'highDay173',
 'openDay173',
 'lowDay173',
 'volumeDay173',
 'closeDay174',
 'highDay174',
 'openDay174',
 'lowDay174',
 'volumeDay174',
 'closeDay175',
 'highDay175',
 'openDay175',
 'lowDay175',
 'volumeDay175',
 'closeDay176',
 'highDay176',
 'openDay176',
 'lowDay176',
 'volumeDay176',
 'closeDay177',
 'highDay177',
 'openDay177',
 'lowDay177',
 'volumeDay177',
 'closeDay178',
 'highDay178',
 'openDay178',
 'lowDay178',
 'volumeDay178',
 'closeDay179',
 'highDay179',
 'openDay179',
 'lowDay179',
 'volumeDay179',
 'closeDay180',
 'highDay180',
 'openDay180',
 'lowDay180',
 'volumeDay180',
 'closeDay181',
 'highDay181',
 'openDay181',
 'lowDay181',
 'volumeDay181',
 'closeDay182',
 'highDay182',
 'openDay182',
 'lowDay182',
 'volumeDay182',
 'closeDay183',
 'highDay183',
 'openDay183',
 'lowDay183',
 'volumeDay183',
 'closeDay184',
 'highDay184',
 'openDay184',
 'lowDay184',
 'volumeDay184',
 'closeDay185',
 'highDay185',
 'openDay185',
 'lowDay185',
 'volumeDay185',
 'closeDay186',
 'highDay186',
 'openDay186',
 'lowDay186',
 'volumeDay186',
 'closeDay187',
 'highDay187',
 'openDay187',
 'lowDay187',
 'volumeDay187',
 'closeDay188',
 'highDay188',
 'openDay188',
 'lowDay188',
 'volumeDay188',
 'closeDay189',
 'highDay189',
 'openDay189',
 'lowDay189',
 'volumeDay189',
 'closeDay190',
 'highDay190',
 'openDay190',
 'lowDay190',
 'volumeDay190',
 'closeDay191',
 'highDay191',
 'openDay191',
 'lowDay191',
 'volumeDay191',
 'closeDay192',
 'highDay192',
 'openDay192',
 'lowDay192',
 'volumeDay192',
 'closeDay193',
 'highDay193',
 'openDay193',
 'lowDay193',
 'volumeDay193',
 'closeDay194',
 'highDay194',
 'openDay194',
 'lowDay194',
 'volumeDay194',
 'closeDay195',
 'highDay195',
 'openDay195',
 'lowDay195',
 'volumeDay195',
 'closeDay196',
 'highDay196',
 'openDay196',
 'lowDay196',
 'volumeDay196',
 'closeDay197',
 'highDay197',
 'openDay197',
 'lowDay197',
 'volumeDay197',
 'closeDay198',
 ...]

In [158]:
filtered = d.filter(['ipoDate', 'openDay0', 'Sector', 'DaysBetterThanSP', 'closeDay100'])
filtered.head()

       ipoDate  openDay0       Sector  DaysBetterThanSP  closeDay100
1    10/2/2014     17.60  Health Care               131        29.38
2    9/26/2013      9.37   Technology               125        12.54
10  12/10/2012     34.91  Health Care               138        45.23
12    5/9/2014     14.83          NaN               112        13.26
17  10/20/2017     19.50  Health Care                70        54.16

In [159]:
filtered.shape

(1597, 5)

In [160]:
filtered.drop(filtered[(filtered['Sector'].isna())].index, inplace = True)
filtered.drop(filtered[(filtered['closeDay100'].isna())].index, inplace = True)
filtered.drop(filtered[(filtered['openDay0'].isna())].index, inplace = True)

In [161]:
filtered.shape

(1265, 5)

In [162]:
filtered.head()

       ipoDate  openDay0       Sector  DaysBetterThanSP  closeDay100
1    10/2/2014     17.60  Health Care               131        29.38
2    9/26/2013      9.37   Technology               125        12.54
10  12/10/2012     34.91  Health Care               138        45.23
17  10/20/2017     19.50  Health Care                70        54.16
19   10/8/2015     22.16      Finance               126        17.50

In [163]:
filtered.rename(columns={'ipoDate': 'date', 'openDay0': 'initialPrice'}, inplace=True)

In [164]:
filtered.rename(columns={'Sector': 'sector', 'DaysBetterThanSP': 'daysBeatSP', 'closeDay100': 'closePrice100'}, inplace=True)

In [165]:
filtered = filtered.loc[(filtered['initialPrice'] >= 4) & (filtered['initialPrice'] < 1000)]

In [166]:
filtered.head()

          date  initialPrice       sector  daysBeatSP  closePrice100
1    10/2/2014         17.60  Health Care         131          29.38
2    9/26/2013          9.37   Technology         125          12.54
10  12/10/2012         34.91  Health Care         138          45.23
17  10/20/2017         19.50  Health Care          70          54.16
19   10/8/2015         22.16      Finance         126          17.50

In [167]:
sp_df = pd.read_csv('sp_values.csv')

In [168]:
sp_df.head()

       date  spvalue
0  1/4/2010  1132.99
1  1/5/2010  1136.52
2  1/6/2010  1137.14
3  1/7/2010  1141.69
4  1/8/2010  1144.98

In [169]:
merged = pd.merge(filtered, sp_df,
                        how="left", on=["date"])
merged.head()

         date  initialPrice       sector  daysBeatSP  closePrice100  spvalue
0   10/2/2014         17.60  Health Care         131          29.38  1946.17
1   9/26/2013          9.37   Technology         125          12.54  1698.67
2  12/10/2012         34.91  Health Care         138          45.23  1418.55
3  10/20/2017         19.50  Health Care          70          54.16  2575.21
4   10/8/2015         22.16      Finance         126          17.50  2013.43

In [170]:
merged['priceChange100Days'] = (merged['closePrice100']-merged['initialPrice'])/(merged['initialPrice'])

In [171]:
merged = merged.drop(['closePrice100', 'date'], axis=1)
merged.head()

   initialPrice       sector  daysBeatSP  spvalue  priceChange100Days
0         17.60  Health Care         131  1946.17            0.669318
1          9.37   Technology         125  1698.67            0.338314
2         34.91  Health Care         138  1418.55            0.295617
3         19.50  Health Care          70  2575.21            1.777436
4         22.16      Finance         126  2013.43           -0.210289

In [172]:
merged.shape

(1238, 5)

In [173]:
merged.to_csv('cleaned_ipo_data.csv', index=False)